{{ $paths := .Values.ingress.paths }}
{{ $urlDict := urlParse .Values.URL }}

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    release: {{ $.Chart.Name }}
  annotations:
{{ .Values.ingress.annotations | toYaml | indent 4 }}
spec:
  rules:
    - host: {{ get (urlParse .Values.URL) "host" }}
      http:
        paths:
{{- if $paths }}
{{ toYaml $paths | indent 10 }}
{{- end }}
{{- end }}
    